# Generated by Django 3.1.6 on 2022-06-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='activated',
            new_name='email_verified',
        ),
    ]
